/*
Problem 2: Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/
#include <stdio.h>
#include <stdlib.h>
int fib(int n);
int main()
{
    int m=1;
    int sum=0;

    while(fib(m)<4000000)
    {
        m++;
        if(fib(m)%2==0)
        {
            sum=sum+fib(m);
        }
    }
    printf("%d\n",sum);
    printf("%d",m);
    return 0;
}
int fib(int n)
{
    int res=0;
    if(n==0)
    {
        res=0;
    }

    if(n==1)
    {
        res=1;
    }
    else if(n==2)
    {
        res=2;
    }
    else

    res = fib(n-1) + fib(n-2);

    return res;
}

